[package]
name = "jot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
config = "0.15.19"
secrecy = { version = "0.10.3", features = ["serde"]}
serde = "1.0.228"
serde-aux = "4.7.0"
sqlx = { version = "0.8.6", features = ["postgres] }
tokio = "1.49.0"
tracing = "0.1.44"
